/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JMicroProyecto;

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import JMicroProyecto.JFrm_Categoria;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Timer;




public class JFrm_Ingresar extends javax.swing.JFrame {
    
    private Component jbtnentrar;
    
    
      private Timer tiempo;
    int cont;
  
    public final static int TWO_SECOND=5;
  
    
    public JFrm_Ingresar() {
        initComponents();
        

        setSize(1500,1000);
        setVisible(true);
       
        
        mdipasa.setVisible(false);
     
        this.setLocationRelativeTo(null);
        setDefaultCloseOperacion(DO_NOTHING_ON_CLOSE);
        barra.setVisible(false);
      
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/p1.jpeg")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno;
        uno = new ImageIcon(this.getClass().getResource("/Imagenes/p1.jpeg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());  

      
        
        
    }

    private void activar() {
        
    }

    private void setDefaultCloseOperacion(int DO_NOTHING_ON_CLOSE) {
    
    }
    class TimerListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ae) 
        {
          cont++;  
          barra.setValue(cont);
          if(cont==100)
          {
            tiempo.stop();
            esconder(); 
              
            JFrm_Categoria Cat = new JFrm_Categoria();
            Cat.setVisible(true);
            setVisible(false);
              
          }
        }

        private void esconder() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        
        
    }
    
    public void iniciosecion(){
    String  usuario1 = "Jerry_Portillo";
    String usuario2="Joam_21";
        String contraseña1 ="87654321";
        String contraseña2="210690";
          String usuario3="Alejandra19";
        String contraseña3 ="19121997";
        
        String Pass = new String (txtpas.getPassword());
        if(txtussuario.getText().equals(usuario1) && Pass.equals(contraseña1))
        {
           
            
        }
         else  if(txtussuario.getText().equals(usuario2) && Pass.equals(contraseña2))
        {
      
            
        }
           else  if(txtussuario.getText().equals(usuario3) && Pass.equals(contraseña3))
        {
        
            
        }
         
        else
        {
            JOptionPane.showMessageDialog(this,"Al parecer su Usuario y su Contraseña son incorrecto "
                                           + "\n el sistema fue cerrado por politica de seguridad");
           
             System.exit(0);
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        button2 = new java.awt.Button();
        mdipasa = new javax.swing.JInternalFrame();
        txtpas = new javax.swing.JPasswordField();
        label1 = new java.awt.Label();
        txtussuario = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        barra = new javax.swing.JProgressBar();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Rosewood Std Regular", 0, 10)); // NOI18N

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(10, 10, 10));
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        label2.setEnabled(false);
        label2.setFont(new java.awt.Font("Edwardian Script ITC", 3, 60)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 153, 0));
        label2.setMaximumSize(new java.awt.Dimension(0, 0));
        label2.setMinimumSize(new java.awt.Dimension(459, 52));
        label2.setText("BIENVENIDOS A CINEPOLIS");

        button2.setBackground(new java.awt.Color(0, 0, 0));
        button2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        button2.setForeground(new java.awt.Color(153, 153, 153));
        button2.setLabel("Entrar");
        button2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button2MouseMoved(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        mdipasa.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(204, 0, 51)));
        mdipasa.setVisible(true);

        txtpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasActionPerformed(evt);
            }
        });
        txtpas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasKeyPressed(evt);
            }
        });

        label1.setText("Password");

        txtussuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtussuarioKeyPressed(evt);
            }
        });

        label3.setText("Usuario");

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mdipasaLayout = new javax.swing.GroupLayout(mdipasa.getContentPane());
        mdipasa.getContentPane().setLayout(mdipasaLayout);
        mdipasaLayout.setHorizontalGroup(
            mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mdipasaLayout.createSequentialGroup()
                .addGroup(mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mdipasaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtussuario)
                            .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mdipasaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mdipasaLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        mdipasaLayout.setVerticalGroup(
            mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mdipasaLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtussuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mdipasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 1446, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(mdipasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(958, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(mdipasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        button2.getAccessibleContext().setAccessibleName("jbtnentrar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        
        
     mdipasa.setVisible(true);
  
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseMoved
     
   
    
    }//GEN-LAST:event_button2MouseMoved

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtpasActionPerformed

    private void txtpasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            JFrm_Categoria cat = new JFrm_Categoria();
            setVisible(false);
        iniciosecion();
        }
    }//GEN-LAST:event_txtpasKeyPressed

    private void txtussuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtussuarioKeyPressed

         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    
              setVisible(false);
        iniciosecion();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtussuarioKeyPressed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_Ingresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton btnsalir;
    private java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JInternalFrame mdipasa;
    private javax.swing.JPasswordField txtpas;
    private javax.swing.JTextField txtussuario;
    // End of variables declaration//GEN-END:variables

    private void getIconWidth() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
